name: SSH Deploy
description: Execute deployment commands over SSH

inputs:
  ssh_private_key:
    description: 'SSH private key'
    required: true
  ssh_user:
    description: 'SSH username'
    required: true
  ssh_host:
    description: 'SSH host'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy via SSH
      shell: bash
      run: |
        # Connect to your server via SSH and execute deployment commands
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cd ~/var/www/api && ./.scripts/deploy.sh'
