name: SSH Deploy
description: Execute deployment commands over SSH

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy via SSH
      shell: bash
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSHKEY }}
        SSH_USER: ${{ secrets.USERNAME }}
        SSH_HOST: ${{ secrets.HOST }}
      run: |
        # Connect to your server via SSH and execute deployment commands
        ssh -o StrictHostKeyChecking=no -i "$SSH_PRIVATE_KEY" "$SSH_USER@$SSH_HOST" 'cd ~/var/www/api && ./.scripts/deploy.sh'
