name: SSH Deploy
description: Execute deployment commands over SSH

inputs:
  ssh_private_key:
    description: 'SSH private key'
    required: true
  ssh_user:
    description: 'SSH username'
    required: true
  ssh_host:
    description: 'SSH host'
    required: true
  ssh_port:
    description: 'SSH port'
    required: false
    default: '22'

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up SSH key
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.ssh_private_key }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa "${{ inputs.ssh_host }}" >> ~/.ssh/known_hosts
    - name: Log in to server
      shell: bash
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -p "${{ inputs.ssh_port }}" "${{ inputs.ssh_user }}@${{ inputs.ssh_host }}"

    - name: Change Directory and Deploy via SSH
      shell: bash
      run: |
        # Connect to your server via SSH and execute deployment commands
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -p "${{ inputs.ssh_port }}" "${{ inputs.ssh_user }}@${{ inputs.ssh_host }}" 'cd ~/var/www/api && ./.scripts/deploy.sh'
        #ssh -t -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -p 22 root@191.101.3.99 'bash -s' < deploy_remote.sh
