name: Deploy

# Trigger the workflow on push and
# pull request events on the master branch
on:
  push:
    branches: ["maim"]
  pull_request:
    branches: ["main"]

# Authenticate to the the server via ssh
# and run our deployment script
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Server
        uses: ./SellAnyHomeBE
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: "cd ~/var/www/api && ./.scripts/deploy.sh"

       #   ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID5A0p1N1vsMbzmndiFsz5ZtzJWlERqct7SjKtRiVpwp github